language: ruby
cache: bundler
rvm:
- 2.2.10
- 2.3.8
- 2.4.6
- 2.5.5
- 2.6.2
- jruby-9.2.5.0
- jruby-9.2.6.0
env:
  global:
    secure: MLkFJDFyxLetmt934cEHRq5u1RMJSZ+SOsSEYq8RtXTW+UjuiWndDn27rKEXRZq8njYKROIZHXtYPZqz7vxFe6oA7zar4cFh9c2/T8N7gp9ekeaSYN3yBP+HzzO0RQeZu69J2VWW0VOua9xrr1e4M1foiRUXeu4+bjqhZQH83TBEahTLnhe3x5UBMVnAAOVPC0R19zVHTESmKCpkFTk+kMCOD4K5BJ3R2NVfAY9KmPqRPh5/jFDkaeOYiMVal466gh/16rK9WbzarqODgJD3Xi32A68K7nbMmGAEbsltQuIxSwrOvP/xmjoikdM9uxxsqSpP+qlfWZL8TUn1EJwRmvXajCE9ak59SAiaieOqfKScouoSajNcTafHdD97y8iFCXqx2b4/QYCrG2RSn8obe0pmHTNQl4mYyGhcnDrmjku+8oGJT007K3Xv5zW6Mm78l2g5HjrbqeDmAQpz1RI6iZyEhOI5ujdv3+jBdIv6KWEaFD1mskHciGB0y0C2YzNa4gSkR5d81tsrsFhbefaq86s11MuDV71YNvTLiy4s3CMeqBSGbZFgEb6LNUsoTbXkRCejdigeg3ZXUpb372tEQhQEHnV7mE4JkXixav6Simfg39N1DPpP4GOpegvIL2SdN7cXpnBEbZ5WILi4ghpf0BnyOTdRjwyMigNCzgtY6NA=
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
